




/*
    Generated by HDL Build
*/
module astep24_3l_top_clocking (
    input  wire				sysclk_in,
    input  wire				warm_resn_in,
    input  wire				cold_resn_in,
    output wire				io_aresn,
    output wire				clk_100,
    output wire				clk_100_resn,
    output wire				clk_core,
    output wire				clk_core_resn,
    output wire				clk_sample,
    output wire				clk_timestamp,
    output wire				clk_uart,
    output wire				clk_uart_resn,
    input  wire				clk_ftdi,
    output wire				clk_ftdi_resn
);

    

    // Reset conditions
    //-----------
    //async_signal_sync  cold_resn_master_sync(.clk(sysclk_in),.async_input(cold_resn_in),.sync_out(cold_resn_in_synced));
    wire all_reset;
    wire shutdown = all_reset && cold_resn_in==0;
    assign io_aresn = !shutdown;
   
    // Clocking
    //------------
        
    // Module Instance
    top_clocking_core_io_uart  top_clocking_core_io_uart_I(
        .clk_in1(sysclk_in),

        .clk_100(clk_100),
        .clk_core(clk_core),
        .clk_sample(clk_sample),
        .clk_timestamp(clk_timestamp),
        .clk_uart(clk_uart),
        .locked(pll_locked),
        .power_down(shutdown),
        .resetn(!shutdown)
    );
            
    wire reset_condition = pll_locked && warm_resn_in && cold_resn_in;
    resets_synchronizer #(.CLOCKS(4),.RESET_DELAY(15)) resets (
        .async_resn_in(reset_condition),
        .input_clocks({clk_ftdi,clk_uart,clk_core,clk_100}),
        .output_resn({clk_ftdi_resn,clk_uart_resn,clk_core_resn,clk_100_resn}),
        .master_all_reset(all_reset)
    );    

endmodule

        
