


/*
    Generated by HDL Build
*/
module housekeeping_main(
    input  wire				clk_core,
    input  wire				clk_core_resn,
    input  wire				clk_spi,
    input  wire				clk_spi_resn,
    output wire [7:0]		ext_adc_miso_m_axis_tdata,
    input  wire				ext_adc_miso_m_axis_tready,
    output wire				ext_adc_miso_m_axis_tvalid,
    output wire [31:0]		ext_adc_miso_read_size,
    input  wire [7:0]		ext_adc_mosi_s_axis_tdata,
    input  wire				ext_adc_mosi_s_axis_tlast,
    output wire				ext_adc_mosi_s_axis_tready,
    input  wire				ext_adc_mosi_s_axis_tvalid,
    output wire				ext_adc_spi_clk,
    output wire				ext_adc_spi_csn,
    input  wire				ext_adc_spi_miso,
    output wire				ext_adc_spi_mosi,
    input  wire [7:0]		ext_dac_mosi_s_axis_tdata,
    input  wire				ext_dac_mosi_s_axis_tlast,
    output wire				ext_dac_mosi_s_axis_tready,
    input  wire				ext_dac_mosi_s_axis_tvalid,
    output wire				ext_dac_spi_clk,
    output wire				ext_dac_spi_csn,
    output wire				ext_dac_spi_mosi,
    input  wire				xadc_conversion_trigger,
    output wire [15:0]		xadc_temperature,
    output wire				xadc_temperature_write,
    output wire [15:0]		xadc_vccint,
    output wire				xadc_vccint_write
);

    // Connections
    //----------------
     

    // Sections
    //---------------


    // Instances
    //------------
        
    // Module Instance
    xadc_hk_driver  xadc_hk_driver_I(
        .clk(clk_core),
        .resn(clk_core_resn),
        .temperature(xadc_temperature),
        .temperature_write(xadc_temperature_write),
        .trigger(xadc_conversion_trigger),
        .vccint(xadc_vccint),
        .vccint_write(xadc_vccint_write)
    );
            
    
    // Module Instance
    ext_adc_driver  ext_adc_driver(
        .clk_core(clk_core),
        .clk_core_resn(clk_core_resn),
        .clk_spi(clk_spi),
        .clk_spi_resn(clk_spi_resn),
        .ext_adc_miso_m_axis_tdata(ext_adc_miso_m_axis_tdata),
        .ext_adc_miso_m_axis_tready(ext_adc_miso_m_axis_tready),
        .ext_adc_miso_m_axis_tvalid(ext_adc_miso_m_axis_tvalid),
        .ext_adc_miso_read_size(ext_adc_miso_read_size),
        .ext_adc_mosi_s_axis_tdata(ext_adc_mosi_s_axis_tdata),
        .ext_adc_mosi_s_axis_tlast(ext_adc_mosi_s_axis_tlast),
        .ext_adc_mosi_s_axis_tready(ext_adc_mosi_s_axis_tready),
        .ext_adc_mosi_s_axis_tvalid(ext_adc_mosi_s_axis_tvalid),
        .ext_adc_spi_clk(ext_adc_spi_clk),
        .ext_adc_spi_csn(ext_adc_spi_csn),
        .ext_adc_spi_miso(ext_adc_spi_miso),
        .ext_adc_spi_mosi(ext_adc_spi_mosi)
    );
            
    
    // Module Instance
    ext_dac_driver  ext_dac_driver(
        .clk_core(clk_core),
        .clk_core_resn(clk_core_resn),
        .clk_spi(clk_spi),
        .clk_spi_resn(clk_spi_resn),
        .ext_dac_mosi_s_axis_tdata(ext_dac_mosi_s_axis_tdata),
        .ext_dac_mosi_s_axis_tlast(ext_dac_mosi_s_axis_tlast),
        .ext_dac_mosi_s_axis_tready(ext_dac_mosi_s_axis_tready),
        .ext_dac_mosi_s_axis_tvalid(ext_dac_mosi_s_axis_tvalid),
        .ext_dac_spi_clk(ext_dac_spi_clk),
        .ext_dac_spi_csn(ext_dac_spi_csn),
        .ext_dac_spi_mosi(ext_dac_spi_mosi)
    );
                

endmodule

        
