


/*
    Generated by HDL Build
*/
module xadc_driver_internal(
    input  wire				adc_alarm_out,
    input  wire				adc_busy_out,
    input  wire [4:0]		adc_channel_out,
    input  wire				adc_eoc_out,
    input  wire				adc_eos_out,
    input  wire				clk,
    input  wire				resn,
    input  wire [15:0]		s_axis_tdata,
    input  wire [4:0]		s_axis_tid,
    output reg				s_axis_tready,
    input  wire				s_axis_tvalid,
    output reg [15:0]		temperature,
    output reg				temperature_write,
    output reg [15:0]		vccint,
    output reg				vccint_write
);

    // Connections
    //----------------
     

    // Sections
    //---------------

            
           
            always@(posedge clk) begin
                if (resn==0) begin 
                    s_axis_tready       <= 1'b0;
                    temperature_write   <= 1'b0;
                    vccint_write        <= 1'b0;
                end else begin 
                    s_axis_tready <= 1'b1;

                    // When a valid value on channel 0 is given, update temperature
                    if (s_axis_tvalid && s_axis_tid==8'h00) begin 
                        temperature_write   <= 1'b1;
                        temperature         <= s_axis_tdata;
                    end else begin
                        temperature_write   <= 1'b0;
                    end

                    if (s_axis_tvalid && s_axis_tid==8'h01) begin 
                        vccint_write        <= 1'b1;
                        vccint              <= s_axis_tdata;
                        
                    end else begin
                        vccint_write <= 1'b0;
                    end
                    

                end
            end
        

    // Instances
    //------------
            

endmodule

        
