


/*
    Generated by HDL Build
*/
module spi_path(
    input  wire				clk_core,
    input  wire				clk_core_resn,
    output wire [7:0]		m_axis_tdata,
    output wire [7:0]		m_axis_tdest,
    output wire [7:0]		m_axis_tid,
    output wire				m_axis_tlast,
    input  wire				m_axis_tready,
    output wire				m_axis_tvalid,
    input  wire [7:0]		s_axis_tdata,
    input  wire [7:0]		s_axis_tdest,
    input  wire [7:0]		s_axis_tid,
    input  wire				s_axis_tlast,
    output wire				s_axis_tready,
    input  wire				s_axis_tvalid,
    input  wire				spi_clk,
    input  wire				spi_csn,
    output wire				spi_miso,
    input  wire				spi_mosi
);

    // Connections
    //----------------
    wire [7:0] spi_igress_m_axis_tdata; // size=8
    wire spi_igress_m_axis_tvalid; // size=1
    wire spi_igress_m_axis_tready; // size=1
    wire [7:0] spi_igress_m_axis_tdest; // size=8
    wire [7:0] spi_igress_m_axis_tid; // size=8
    wire egress_fifo_m_axis_tvalid; // size=1
    wire egress_fifo_m_axis_tready; // size=1
    wire [7:0] egress_fifo_m_axis_tdata; // size=8
    wire egress_fifo_m_axis_tlast; // size=1
    wire [7:0] egress_fifo_m_axis_tid; // size=8
    wire [7:0] readout_framing_m_axis_tdata; // size=8
    wire readout_framing_m_axis_tvalid; // size=1
    wire readout_framing_m_axis_tready; // size=1
    wire [7:0] readout_framing_m_axis_tuser; // size=8 

    // Sections
    //---------------


    // Instances
    //------------
        
    // Module Instance
    spi_slave_axis_igress #(.DEST_WIDTH(8),.ID_WIDTH(8),.AXIS_DEST(0),.AXIS_SOURCE(2),.ASYNC_RES(1),.USE_CHIP_SELECT(0),.MSB_FIRST(1)) spi_igress(
        .err_overrun(/* WAIVED: Overrun not relevant when CS not used */),
        .m_axis_tdata(spi_igress_m_axis_tdata),
        .m_axis_tdest(spi_igress_m_axis_tdest),
        .m_axis_tid(spi_igress_m_axis_tid),
        .m_axis_tready(spi_igress_m_axis_tready),
        .m_axis_tvalid(spi_igress_m_axis_tvalid),
        .resn(spi_csn),
        .spi_clk(spi_clk),
        .spi_csn(spi_csn),
        .spi_mosi(spi_mosi)
    );
            
    
    // Module Instance
    fifo_axis_2clk_sw_io_16e  igress_fifo(
        .m_axis_aclk(clk_core),
        .m_axis_tdata(m_axis_tdata),
        .m_axis_tdest(m_axis_tdest),
        .m_axis_tid(m_axis_tid),
        //.m_axis_tlast(m_axis_tlast),
        .m_axis_tready(m_axis_tready),
        .m_axis_tvalid(m_axis_tvalid),
        .s_axis_aclk(spi_clk),
        .s_axis_aresetn(spi_csn),
        .s_axis_tdata(spi_igress_m_axis_tdata),
        .s_axis_tdest(spi_igress_m_axis_tdest),
        .s_axis_tid(spi_igress_m_axis_tid),
        //.s_axis_tlast(1'd1),
        .s_axis_tready(spi_igress_m_axis_tready),
        .s_axis_tvalid(spi_igress_m_axis_tvalid)
    );
            
    
    // Module Instance
    fifo_axis_2clk_sw_io_16e  egress_fifo(
        .m_axis_aclk(spi_clk),
        .m_axis_tdata(egress_fifo_m_axis_tdata),
        .m_axis_tdest(/* WAIVED: Byte Egress has not routing/vid capacity */),
        .m_axis_tid(egress_fifo_m_axis_tid),
        //.m_axis_tlast(egress_fifo_m_axis_tlast),
        .m_axis_tready(egress_fifo_m_axis_tready),
        .m_axis_tvalid(egress_fifo_m_axis_tvalid),
        .s_axis_aclk(clk_core),
        .s_axis_aresetn(clk_core_resn),
        .s_axis_tdata(s_axis_tdata),
        .s_axis_tdest(s_axis_tdest),
        .s_axis_tid(s_axis_tid),
        //.s_axis_tlast(s_axis_tlast),
        .s_axis_tready(s_axis_tready),
        .s_axis_tvalid(s_axis_tvalid)
    );
            
    
    // Module Instance
    rfg_axis_readout_framing #(.MTU_SIZE(16),.IDLE_BYTE(8'hBC),.START_BYTE(8'hEF)) readout_framing(
        .clk(spi_clk),
        .m_axis_tdata(readout_framing_m_axis_tdata),
        .m_axis_tready(readout_framing_m_axis_tready),
        .m_axis_tuser(readout_framing_m_axis_tuser),
        .m_axis_tvalid(readout_framing_m_axis_tvalid),
        .resn(spi_csn),
        .s_axis_tdata(egress_fifo_m_axis_tdata),
        .s_axis_tid(egress_fifo_m_axis_tid),
        .s_axis_tlast(egress_fifo_m_axis_tlast),
        .s_axis_tready(egress_fifo_m_axis_tready),
        .s_axis_tvalid(egress_fifo_m_axis_tvalid)
    );
            
    
    // Module Instance
    spi_slave_axis_egress #(.ASYNC_RES(1),.MSB_FIRST(1),.MISO_SIZE(1),.MTU_SIZE(16),.USE_CHIP_SELECT(0)) spi_egress(
        .resn(spi_csn),
        .s_axis_tdata(readout_framing_m_axis_tdata),
        .s_axis_tready(readout_framing_m_axis_tready),
        .s_axis_tuser(readout_framing_m_axis_tuser),
        .s_axis_tvalid(readout_framing_m_axis_tvalid),
        .spi_clk(spi_clk),
        .spi_csn(spi_csn),
        .spi_miso(spi_miso)
    );
                

endmodule

        
