


/*
    Generated by HDL Build
*/
module sw_switch(
    input  wire				clk,
    output wire [7:0]		m_axis_0_tdata,
    output wire [7:0]		m_axis_0_tdest,
    output wire [7:0]		m_axis_0_tid,
    output wire				m_axis_0_tlast,
    input  wire				m_axis_0_tready,
    output wire				m_axis_0_tuser,
    output wire				m_axis_0_tvalid,
    output wire [7:0]		m_axis_1_tdata,
    output wire [7:0]		m_axis_1_tdest,
    output wire [7:0]		m_axis_1_tid,
    output wire				m_axis_1_tlast,
    input  wire				m_axis_1_tready,
    output wire				m_axis_1_tuser,
    output wire				m_axis_1_tvalid,
    output wire [7:0]		m_axis_2_tdata,
    output wire [7:0]		m_axis_2_tdest,
    output wire [7:0]		m_axis_2_tid,
    output wire				m_axis_2_tlast,
    input  wire				m_axis_2_tready,
    output wire				m_axis_2_tuser,
    output wire				m_axis_2_tvalid,
    input  wire				resn,
    input  wire [7:0]		s_axis_0_tdata,
    input  wire [7:0]		s_axis_0_tdest,
    input  wire [7:0]		s_axis_0_tid,
    input  wire				s_axis_0_tlast,
    output wire				s_axis_0_tready,
    input  wire				s_axis_0_tuser,
    input  wire				s_axis_0_tvalid,
    input  wire [7:0]		s_axis_1_tdata,
    input  wire [7:0]		s_axis_1_tdest,
    input  wire [7:0]		s_axis_1_tid,
    input  wire				s_axis_1_tlast,
    output wire				s_axis_1_tready,
    input  wire				s_axis_1_tuser,
    input  wire				s_axis_1_tvalid,
    input  wire [7:0]		s_axis_2_tdata,
    input  wire [7:0]		s_axis_2_tdest,
    input  wire [7:0]		s_axis_2_tid,
    input  wire				s_axis_2_tlast,
    output wire				s_axis_2_tready,
    input  wire				s_axis_2_tuser,
    input  wire				s_axis_2_tvalid,
    output wire [2:0]		s_decode_err
);

    // Connections
    //----------------
     

    // Sections
    //---------------


    // Instances
    //------------
        
    // Module Instance
    axis_switch_swifs  axis_switch_swifs_I(
        .aclk(clk),
        .aresetn(resn),
        .m_axis_tdata({m_axis_2_tdata,m_axis_1_tdata,m_axis_0_tdata}),
        .m_axis_tdest({m_axis_2_tdest,m_axis_1_tdest,m_axis_0_tdest}),
        .m_axis_tid({m_axis_2_tid,m_axis_1_tid,m_axis_0_tid}),
        .m_axis_tlast({m_axis_2_tlast,m_axis_1_tlast,m_axis_0_tlast}),
        .m_axis_tready({m_axis_2_tready,m_axis_1_tready,m_axis_0_tready}),
        .m_axis_tuser({m_axis_2_tuser,m_axis_1_tuser,m_axis_0_tuser}),
        .m_axis_tvalid({m_axis_2_tvalid,m_axis_1_tvalid,m_axis_0_tvalid}),
        .s_axis_tdata({s_axis_2_tdata,s_axis_1_tdata,s_axis_0_tdata}),
        .s_axis_tdest({s_axis_2_tdest,s_axis_1_tdest,s_axis_0_tdest}),
        .s_axis_tid({s_axis_2_tid,s_axis_1_tid,s_axis_0_tid}),
        .s_axis_tlast({s_axis_2_tlast,s_axis_1_tlast,s_axis_0_tlast}),
        .s_axis_tready({s_axis_2_tready,s_axis_1_tready,s_axis_0_tready}),
        .s_axis_tuser({s_axis_2_tuser,s_axis_1_tuser,s_axis_0_tuser}),
        .s_axis_tvalid({s_axis_2_tvalid,s_axis_1_tvalid,s_axis_0_tvalid}),
        .s_decode_err(s_decode_err)
    );
                

endmodule

        
